CREATE TABLE mi.t_client_attributes (
     client_corporation_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
    ,client_type TEXT 
    ,client_probability TEXT 
    ,client_recruitment TEXT 
    ,client_relations TEXT  
    ,mod_date TIMESTAMP
)

