CREATE TABLE mi.t_vacancy_attributes (
     vacancy_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
    ,vacancy_priority INT 
    ,vacancy_exception TEXT 
    ,vacancy_exception_comment TEXT 
    ,mod_date TIMESTAMP
)

